version: '3.8'

services:
  python-api:
    build:
      context: .
      dockerfile: py.dockerfile
    ports:
      - "8000:8000"
  java-api:
    build:
      context: .
      dockerfile: java.dockerfile
    ports:
      - "8080:8080"
  

  

